type = 'csharp'
client-type = "js"
client-files = [
    'Client/locales/zh_hans.json',
    'Client/locales/zh_hant.json',
    'Client/webview/*',
    'Client/dist/client.js',
    'Client/nametag/*'
]
client-main = 'Client/dist/client.js'
main = 'Server/src/bin/Debug/net6.0/src.dll'